const countryNameMap = {
    "Holy See": "Vatican",
    "United States of America": "United States",
    "South Korea": "Republic of Korea",
    "North Korea": "Democratic People's Republic of Korea",
    "Czech Republic": "Czechia",
    "Russia": "Russian Federation",
    "Syria": "Syrian Arab Republic",
    "Iran": "Islamic Republic of Iran",
    "Bolivia": "Bolivia (Plurinational State of)",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Laos": "Lao People's Democratic Republic",
    "Brunei": "Brunei Darussalam",
    "Tanzania": "United Republic of Tanzania",
    "Moldova": "Republic of Moldova",
    "Macedonia": "North Macedonia",
    "Ivory Coast": "Côte d'Ivoire",
    "Cape Verde": "Cabo Verde",
    "Swaziland": "Eswatini",
    "Burma": "Myanmar",
    "Micronesia": "Federated States of Micronesia",
    "Gambia": "The Gambia",
    "Bahamas": "The Bahamas",
    "East Timor": "Timor-Leste",
    "Palestine": "State of Palestine",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Antigua and Barbuda": "Antigua & Barbuda",
    "Bosnia and Herzegovina": "Bosnia & Herzegovina",
    "Trinidad and Tobago": "Trinidad & Tobago",
    "United Arab Emirates": "UAE",
    "St. Kitts and Nevis": "Saint Kitts & Nevis",
    "St. Vincent and the Grenadines": "Saint Vincent & the Grenadines",
    "Solomon Islands": "Solomon Is.",
    "Marshall Islands": "Marshall Is.",
    "St. Lucia": "Saint Lucia",
    "Democratic Republic of the Congo": "DR Congo",
    "Congo": "Congo-Brazzaville",
    "Guinea-Bissau": "Guinea Bissau",
    "Burkina Faso": "Burkina",
    "Western Sahara": "Sahrawi Arab Democratic Republic",
    "North Macedonia": "Macedonia",
    "United Kingdom": "UK",
    "Sint Maarten": "Sint Maarten (Dutch part)",
    "Timor-Leste": "East Timor",
    "South Sudan": "Republic of South Sudan",
    "Cabo Verde": "Cape Verde",
    "Curacao": "Curaçao",
    "Saint Barthelemy": "Saint Barthélemy",
    "Guinea-Bissau": "Guinea Bissau",
    "Taiwan": "Taiwan Province of China",
    "Macau": "Macao",
    "Vietnam": "Viet Nam",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Falkland Islands": "Falkland Islands (Malvinas)",
    "Isle of Man": "Isle of Man",
    "Western Sahara": "Sahrawi Arab Democratic Republic",
    "French Southern and Antarctic Lands": "French Southern Territories",
    "Czechia": "Czech Republic",
    "Eswatini": "Swaziland",
    "Ivory Coast": "Côte d'Ivoire",
    "Côte d'Ivoire": "Ivory Coast",
    "DR Congo": "Democratic Republic of the Congo",
    "Republic of Korea": "South Korea",
    "Democratic People's Republic of Korea": "North Korea",
    "U.S. Virgin Islands": "United States Virgin Islands",
    "Northern Mariana Islands": "N. Mariana Is.",
    "Guinea Bissau": "Guinea-Bissau",
    "United Republic of Tanzania": "Tanzania",
    "Lao People's Democratic Republic": "Laos",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Iran (Islamic Republic of)": "Iran",
    "Russian Federation": "Russia",
    "Syrian Arab Republic": "Syria",
    "United States Minor Outlying Islands": "United States Minor Islands",
    "Saint Martin (French part)": "Saint Martin",
    "Bahamas": "The Bahamas",
    "Gambia": "The Gambia",
    "Guam": "Guam",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Myanmar": "Burma",
    "Republic of Moldova": "Moldova",
    "North Macedonia": "Macedonia",
    "Timor-Leste": "East Timor",
    "Cabo Verde": "Cape Verde",
    "Brunei Darussalam": "Brunei",
    "Micronesia (Federated States of)": "Micronesia",
    "Tonga": "Kingdom of Tonga",
    "Niger": "Republic of Niger",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Antigua and Barbuda": "Antigua & Barbuda",
    "Saint Lucia": "Saint Lucia",
    "Marshall Islands": "Marshall Is.",
    "Solomon Islands": "Solomon Is.",
    "United Arab Emirates": "UAE",
    "Vatican City": "Holy See",
};

export default countryNameMap;
